### ISSUE TITLE
Failed to parse Hetero-atom only file

### ISSUE THREAD

**Issue by nezix** [cameronabrams/pidibble#1]
Reading a PDB file with HETATM and CONECT fields only, returns empty parsed dictionary

```
from pidibble.pdbparse import PDBParser
p = PDBParser(pdb_code="50D_5ceo.pdb").parse()
```

[50D_5ceo.zip](https://github.com/cameronabrams/pidibble/files/13219740/50D_5ceo.zip)

Edit: Reading the code, it seems that it does not support reading local files

**Comment by cameronabrams** [comment]
Unfortunately I made the keyword confusing.  Use

```
from pidibble.pdbparse import PDBParser1
p = PDBParser(PDBcode="50D_5ceo").parse()
```

That is, the keyword argument for the `pdb_code` member is `PDBcode`, and the `.pdb` suffix is automatically added.
